// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BookingService
{
    public Guid Id { get; set; }

    public Guid BookingId { get; set; }

    public Guid ServiceId { get; set; }

    public int? Quantity { get; set; }

    public decimal? PriceAtBooking { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Service Service { get; set; }
}