// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class ChatRoom
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid? SupportId { get; set; }

    public string LastMessage { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual User Support { get; set; }

    public virtual User User { get; set; }
}