// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class ChatMessage
{
    public Guid Id { get; set; }

    public Guid ChatRoomId { get; set; }

    public Guid SenderId { get; set; }

    public string MessageText { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }

    public virtual User Sender { get; set; }
}