// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;
public partial class Service
{
    public Guid Id { get; set; }

    public string ServiceName { get; set; }

    public decimal Price { get; set; }

    public string Unit { get; set; }

    public int? StockQuantity { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BookingService> BookingServices { get; set; } = new List<BookingService>();
}